apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key:  topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
          # - key:  disktype
          #   operator: In
          #   values:
          #   - ssd
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchExpressions:
            - key: course
              operator: In
              values:
              - linux
        - weight: 100
          preference:
            matchExpressions:
            - key: course
              operator: In
              values:
              - ansible
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
